### ISSUE TITLE
Babel 6?

### ISSUE THREAD

**Issue by dantman** [jquense/react-component-metadata#4]
Do you have plans to update this to babel 6?

I wanted to update react-big-calendar to use it, but discovered this required babel 5, then I spent some time updating this to discover that use of babel is wired so deep I cannot just write the code to update it to babel 6 for you.

**Comment by jquense** [comment]
There are too many babel 5 api's at use here to quickly upgrade, as you saw, and I don't have the will power right now to upgrade. That being said, This should probably just remove babel-core as a peer dependency since this isn't actually a plugin in the general sense, its more of a tool built on top of babel.

**Comment by bjrn** [comment]
@dantman I believe there's support for Babel 6 in v3.0.0?

**Comment by jquense** [comment]
yes, thanks for the reminder. closing
